kind: Service
apiVersion: v1
metadata:
  name: greenhouse-service-${CICD_EXECUTION_SEQUENCE}
spec:
  selector:
    app: greenhouse-${CICD_EXECUTION_SEQUENCE}
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-greenhouse-${CICD_EXECUTION_SEQUENCE}
  labels:
    app: greenhouse-${CICD_EXECUTION_SEQUENCE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenhouse-${CICD_EXECUTION_SEQUENCE}
  template:
    metadata:
      labels:
        app: greenhouse-${CICD_EXECUTION_SEQUENCE}
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: maven
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
